[template]
name = "basic"


notes = """
	Added the {{tutorial_name}} to your XDP Project {{name}}.

	The Goal of this XDP tutorial is to introduce the concept of eBPF Maps and how they can be used
	by XDP programs for different packet processing actions.

	In this program, we are introducing a very simple Packet counter that -
        1. Counts the number of Packets that match XDP_PASS action.

	This tutorial also explores the concepts of how to use atomics inside the eBPF kernel code.

	Next, as an assignment we will take a look at different kind of Map called Per CPU Array and
	how that Map can be used.
"""
[hooks]
pre = [ "mkdir {{tutorial_name}}" ]

post = [ "mv README.md {{tutorial_name}}-ebpf common xdp-runner {{tutorial_name}}" ]


[parameters]
	[parameters.tutorial_name]
	type = "string"
	message = "Name of the tutorial to use in XDP Project (default: 'basic-03')"
	default = "basic-03"
