[template]
name = "basic"


notes = """
	Added the {{tutorial_name}} to your XDP Project {{name}}
"""

[parameters]
	[parameters.tutorial_name]
	type = "string"
	message = "Name of the tutorial to compile?"
	required = true
