[package]
name = "{{ name }}-xtask"
version = "0.1.0"
edition = "2021"
default-run = "xtask"

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }

[lib]
name = "xtask"
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"

